//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirWebService.servicioCasasAsmx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Casas", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Casas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipodeCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private System.Nullable<int> DueñoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private consumirWebService.servicioCasasAsmx.Dueños DueñosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCasa {
            get {
                return this.idCasaField;
            }
            set {
                if ((this.idCasaField.Equals(value) != true)) {
                    this.idCasaField = value;
                    this.RaisePropertyChanged("idCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipodeCasa {
            get {
                return this.tipodeCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipodeCasaField, value) != true)) {
                    this.tipodeCasaField = value;
                    this.RaisePropertyChanged("tipodeCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Dueño {
            get {
                return this.DueñoField;
            }
            set {
                if ((this.DueñoField.Equals(value) != true)) {
                    this.DueñoField = value;
                    this.RaisePropertyChanged("Dueño");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public consumirWebService.servicioCasasAsmx.Dueños Dueños {
            get {
                return this.DueñosField;
            }
            set {
                if ((object.ReferenceEquals(this.DueñosField, value) != true)) {
                    this.DueñosField = value;
                    this.RaisePropertyChanged("Dueños");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dueños", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Dueños : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idDueñoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private consumirWebService.servicioCasasAsmx.Casas[] CasasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idDueño {
            get {
                return this.idDueñoField;
            }
            set {
                if ((this.idDueñoField.Equals(value) != true)) {
                    this.idDueñoField = value;
                    this.RaisePropertyChanged("idDueño");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public consumirWebService.servicioCasasAsmx.Casas[] Casas {
            get {
                return this.CasasField;
            }
            set {
                if ((object.ReferenceEquals(this.CasasField, value) != true)) {
                    this.CasasField = value;
                    this.RaisePropertyChanged("Casas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioCasasAsmx.servicioAsmxCasasSoap")]
    public interface servicioAsmxCasasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento registrosCasasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrosCasas", ReplyAction="*")]
        consumirWebService.servicioCasasAsmx.registrosCasasResponse registrosCasas(consumirWebService.servicioCasasAsmx.registrosCasasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrosCasas", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.registrosCasasResponse> registrosCasasAsync(consumirWebService.servicioCasasAsmx.registrosCasasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento seleccionarCasaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarCasa", ReplyAction="*")]
        consumirWebService.servicioCasasAsmx.seleccionarCasaResponse seleccionarCasa(consumirWebService.servicioCasasAsmx.seleccionarCasaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarCasa", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.seleccionarCasaResponse> seleccionarCasaAsync(consumirWebService.servicioCasasAsmx.seleccionarCasaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento insCasa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarCasa", ReplyAction="*")]
        consumirWebService.servicioCasasAsmx.insertarCasaResponse insertarCasa(consumirWebService.servicioCasasAsmx.insertarCasaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarCasa", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.insertarCasaResponse> insertarCasaAsync(consumirWebService.servicioCasasAsmx.insertarCasaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento modCasas del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarCasa", ReplyAction="*")]
        consumirWebService.servicioCasasAsmx.ModificarCasaResponse ModificarCasa(consumirWebService.servicioCasasAsmx.ModificarCasaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarCasa", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.ModificarCasaResponse> ModificarCasaAsync(consumirWebService.servicioCasasAsmx.ModificarCasaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCasa", ReplyAction="*")]
        bool eliminarCasa(int eliCasa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarCasa", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminarCasaAsync(int eliCasa);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrosCasasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrosCasas", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.registrosCasasRequestBody Body;
        
        public registrosCasasRequest() {
        }
        
        public registrosCasasRequest(consumirWebService.servicioCasasAsmx.registrosCasasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registrosCasasRequestBody {
        
        public registrosCasasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrosCasasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrosCasasResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.registrosCasasResponseBody Body;
        
        public registrosCasasResponse() {
        }
        
        public registrosCasasResponse(consumirWebService.servicioCasasAsmx.registrosCasasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrosCasasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioCasasAsmx.Casas[] registrosCasasResult;
        
        public registrosCasasResponseBody() {
        }
        
        public registrosCasasResponseBody(consumirWebService.servicioCasasAsmx.Casas[] registrosCasasResult) {
            this.registrosCasasResult = registrosCasasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarCasaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarCasa", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.seleccionarCasaRequestBody Body;
        
        public seleccionarCasaRequest() {
        }
        
        public seleccionarCasaRequest(consumirWebService.servicioCasasAsmx.seleccionarCasaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarCasaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public seleccionarCasaRequestBody() {
        }
        
        public seleccionarCasaRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarCasaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarCasaResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.seleccionarCasaResponseBody Body;
        
        public seleccionarCasaResponse() {
        }
        
        public seleccionarCasaResponse(consumirWebService.servicioCasasAsmx.seleccionarCasaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarCasaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioCasasAsmx.Casas seleccionarCasaResult;
        
        public seleccionarCasaResponseBody() {
        }
        
        public seleccionarCasaResponseBody(consumirWebService.servicioCasasAsmx.Casas seleccionarCasaResult) {
            this.seleccionarCasaResult = seleccionarCasaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCasaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCasa", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.insertarCasaRequestBody Body;
        
        public insertarCasaRequest() {
        }
        
        public insertarCasaRequest(consumirWebService.servicioCasasAsmx.insertarCasaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarCasaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioCasasAsmx.Casas insCasa;
        
        public insertarCasaRequestBody() {
        }
        
        public insertarCasaRequestBody(consumirWebService.servicioCasasAsmx.Casas insCasa) {
            this.insCasa = insCasa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCasaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCasaResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.insertarCasaResponseBody Body;
        
        public insertarCasaResponse() {
        }
        
        public insertarCasaResponse(consumirWebService.servicioCasasAsmx.insertarCasaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarCasaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarCasaResult;
        
        public insertarCasaResponseBody() {
        }
        
        public insertarCasaResponseBody(bool insertarCasaResult) {
            this.insertarCasaResult = insertarCasaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarCasaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarCasa", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.ModificarCasaRequestBody Body;
        
        public ModificarCasaRequest() {
        }
        
        public ModificarCasaRequest(consumirWebService.servicioCasasAsmx.ModificarCasaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarCasaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioCasasAsmx.Casas modCasas;
        
        public ModificarCasaRequestBody() {
        }
        
        public ModificarCasaRequestBody(consumirWebService.servicioCasasAsmx.Casas modCasas) {
            this.modCasas = modCasas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarCasaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarCasaResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioCasasAsmx.ModificarCasaResponseBody Body;
        
        public ModificarCasaResponse() {
        }
        
        public ModificarCasaResponse(consumirWebService.servicioCasasAsmx.ModificarCasaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarCasaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarCasaResult;
        
        public ModificarCasaResponseBody() {
        }
        
        public ModificarCasaResponseBody(bool ModificarCasaResult) {
            this.ModificarCasaResult = ModificarCasaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioAsmxCasasSoapChannel : consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioAsmxCasasSoapClient : System.ServiceModel.ClientBase<consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap>, consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap {
        
        public servicioAsmxCasasSoapClient() {
        }
        
        public servicioAsmxCasasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioAsmxCasasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioAsmxCasasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioAsmxCasasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioCasasAsmx.registrosCasasResponse consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.registrosCasas(consumirWebService.servicioCasasAsmx.registrosCasasRequest request) {
            return base.Channel.registrosCasas(request);
        }
        
        public consumirWebService.servicioCasasAsmx.Casas[] registrosCasas() {
            consumirWebService.servicioCasasAsmx.registrosCasasRequest inValue = new consumirWebService.servicioCasasAsmx.registrosCasasRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.registrosCasasRequestBody();
            consumirWebService.servicioCasasAsmx.registrosCasasResponse retVal = ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).registrosCasas(inValue);
            return retVal.Body.registrosCasasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.registrosCasasResponse> consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.registrosCasasAsync(consumirWebService.servicioCasasAsmx.registrosCasasRequest request) {
            return base.Channel.registrosCasasAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.registrosCasasResponse> registrosCasasAsync() {
            consumirWebService.servicioCasasAsmx.registrosCasasRequest inValue = new consumirWebService.servicioCasasAsmx.registrosCasasRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.registrosCasasRequestBody();
            return ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).registrosCasasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioCasasAsmx.seleccionarCasaResponse consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.seleccionarCasa(consumirWebService.servicioCasasAsmx.seleccionarCasaRequest request) {
            return base.Channel.seleccionarCasa(request);
        }
        
        public consumirWebService.servicioCasasAsmx.Casas seleccionarCasa(int id) {
            consumirWebService.servicioCasasAsmx.seleccionarCasaRequest inValue = new consumirWebService.servicioCasasAsmx.seleccionarCasaRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.seleccionarCasaRequestBody();
            inValue.Body.id = id;
            consumirWebService.servicioCasasAsmx.seleccionarCasaResponse retVal = ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).seleccionarCasa(inValue);
            return retVal.Body.seleccionarCasaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.seleccionarCasaResponse> consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.seleccionarCasaAsync(consumirWebService.servicioCasasAsmx.seleccionarCasaRequest request) {
            return base.Channel.seleccionarCasaAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.seleccionarCasaResponse> seleccionarCasaAsync(int id) {
            consumirWebService.servicioCasasAsmx.seleccionarCasaRequest inValue = new consumirWebService.servicioCasasAsmx.seleccionarCasaRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.seleccionarCasaRequestBody();
            inValue.Body.id = id;
            return ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).seleccionarCasaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioCasasAsmx.insertarCasaResponse consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.insertarCasa(consumirWebService.servicioCasasAsmx.insertarCasaRequest request) {
            return base.Channel.insertarCasa(request);
        }
        
        public bool insertarCasa(consumirWebService.servicioCasasAsmx.Casas insCasa) {
            consumirWebService.servicioCasasAsmx.insertarCasaRequest inValue = new consumirWebService.servicioCasasAsmx.insertarCasaRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.insertarCasaRequestBody();
            inValue.Body.insCasa = insCasa;
            consumirWebService.servicioCasasAsmx.insertarCasaResponse retVal = ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).insertarCasa(inValue);
            return retVal.Body.insertarCasaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.insertarCasaResponse> consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.insertarCasaAsync(consumirWebService.servicioCasasAsmx.insertarCasaRequest request) {
            return base.Channel.insertarCasaAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.insertarCasaResponse> insertarCasaAsync(consumirWebService.servicioCasasAsmx.Casas insCasa) {
            consumirWebService.servicioCasasAsmx.insertarCasaRequest inValue = new consumirWebService.servicioCasasAsmx.insertarCasaRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.insertarCasaRequestBody();
            inValue.Body.insCasa = insCasa;
            return ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).insertarCasaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioCasasAsmx.ModificarCasaResponse consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.ModificarCasa(consumirWebService.servicioCasasAsmx.ModificarCasaRequest request) {
            return base.Channel.ModificarCasa(request);
        }
        
        public bool ModificarCasa(consumirWebService.servicioCasasAsmx.Casas modCasas) {
            consumirWebService.servicioCasasAsmx.ModificarCasaRequest inValue = new consumirWebService.servicioCasasAsmx.ModificarCasaRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.ModificarCasaRequestBody();
            inValue.Body.modCasas = modCasas;
            consumirWebService.servicioCasasAsmx.ModificarCasaResponse retVal = ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).ModificarCasa(inValue);
            return retVal.Body.ModificarCasaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.ModificarCasaResponse> consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap.ModificarCasaAsync(consumirWebService.servicioCasasAsmx.ModificarCasaRequest request) {
            return base.Channel.ModificarCasaAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioCasasAsmx.ModificarCasaResponse> ModificarCasaAsync(consumirWebService.servicioCasasAsmx.Casas modCasas) {
            consumirWebService.servicioCasasAsmx.ModificarCasaRequest inValue = new consumirWebService.servicioCasasAsmx.ModificarCasaRequest();
            inValue.Body = new consumirWebService.servicioCasasAsmx.ModificarCasaRequestBody();
            inValue.Body.modCasas = modCasas;
            return ((consumirWebService.servicioCasasAsmx.servicioAsmxCasasSoap)(this)).ModificarCasaAsync(inValue);
        }
        
        public bool eliminarCasa(int eliCasa) {
            return base.Channel.eliminarCasa(eliCasa);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarCasaAsync(int eliCasa) {
            return base.Channel.eliminarCasaAsync(eliCasa);
        }
    }
}
