//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consumirWebService.servicioAsmx {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dueños", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Dueños : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idDueñoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private int EdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private consumirWebService.servicioAsmx.Casas[] CasasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idDueño {
            get {
                return this.idDueñoField;
            }
            set {
                if ((this.idDueñoField.Equals(value) != true)) {
                    this.idDueñoField = value;
                    this.RaisePropertyChanged("idDueño");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Edad {
            get {
                return this.EdadField;
            }
            set {
                if ((this.EdadField.Equals(value) != true)) {
                    this.EdadField = value;
                    this.RaisePropertyChanged("Edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public consumirWebService.servicioAsmx.Casas[] Casas {
            get {
                return this.CasasField;
            }
            set {
                if ((object.ReferenceEquals(this.CasasField, value) != true)) {
                    this.CasasField = value;
                    this.RaisePropertyChanged("Casas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Casas", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Casas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipodeCasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private System.Nullable<int> DueñoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private consumirWebService.servicioAsmx.Dueños DueñosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idCasa {
            get {
                return this.idCasaField;
            }
            set {
                if ((this.idCasaField.Equals(value) != true)) {
                    this.idCasaField = value;
                    this.RaisePropertyChanged("idCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipodeCasa {
            get {
                return this.tipodeCasaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipodeCasaField, value) != true)) {
                    this.tipodeCasaField = value;
                    this.RaisePropertyChanged("tipodeCasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> Dueño {
            get {
                return this.DueñoField;
            }
            set {
                if ((this.DueñoField.Equals(value) != true)) {
                    this.DueñoField = value;
                    this.RaisePropertyChanged("Dueño");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public consumirWebService.servicioAsmx.Dueños Dueños {
            get {
                return this.DueñosField;
            }
            set {
                if ((object.ReferenceEquals(this.DueñosField, value) != true)) {
                    this.DueñosField = value;
                    this.RaisePropertyChanged("Dueños");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioAsmx.servicioAsmxDueñosSoap")]
    public interface servicioAsmxDueñosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento registrosDueñosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrosDueños", ReplyAction="*")]
        consumirWebService.servicioAsmx.registrosDueñosResponse registrosDueños(consumirWebService.servicioAsmx.registrosDueñosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrosDueños", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.registrosDueñosResponse> registrosDueñosAsync(consumirWebService.servicioAsmx.registrosDueñosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento seleccionarDueñoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarDueño", ReplyAction="*")]
        consumirWebService.servicioAsmx.seleccionarDueñoResponse seleccionarDueño(consumirWebService.servicioAsmx.seleccionarDueñoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seleccionarDueño", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.seleccionarDueñoResponse> seleccionarDueñoAsync(consumirWebService.servicioAsmx.seleccionarDueñoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento insDueño del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDueño", ReplyAction="*")]
        consumirWebService.servicioAsmx.insertarDueñoResponse insertarDueño(consumirWebService.servicioAsmx.insertarDueñoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarDueño", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.insertarDueñoResponse> insertarDueñoAsync(consumirWebService.servicioAsmx.insertarDueñoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento modDueño del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarDueño", ReplyAction="*")]
        consumirWebService.servicioAsmx.ModificarDueñoResponse ModificarDueño(consumirWebService.servicioAsmx.ModificarDueñoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarDueño", ReplyAction="*")]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.ModificarDueñoResponse> ModificarDueñoAsync(consumirWebService.servicioAsmx.ModificarDueñoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDueño", ReplyAction="*")]
        bool eliminarDueño(int eliDueño);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDueño", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminarDueñoAsync(int eliDueño);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrosDueñosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrosDueños", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.registrosDueñosRequestBody Body;
        
        public registrosDueñosRequest() {
        }
        
        public registrosDueñosRequest(consumirWebService.servicioAsmx.registrosDueñosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registrosDueñosRequestBody {
        
        public registrosDueñosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrosDueñosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrosDueñosResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.registrosDueñosResponseBody Body;
        
        public registrosDueñosResponse() {
        }
        
        public registrosDueñosResponse(consumirWebService.servicioAsmx.registrosDueñosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrosDueñosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioAsmx.Dueños[] registrosDueñosResult;
        
        public registrosDueñosResponseBody() {
        }
        
        public registrosDueñosResponseBody(consumirWebService.servicioAsmx.Dueños[] registrosDueñosResult) {
            this.registrosDueñosResult = registrosDueñosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarDueñoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarDueño", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.seleccionarDueñoRequestBody Body;
        
        public seleccionarDueñoRequest() {
        }
        
        public seleccionarDueñoRequest(consumirWebService.servicioAsmx.seleccionarDueñoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarDueñoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public seleccionarDueñoRequestBody() {
        }
        
        public seleccionarDueñoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seleccionarDueñoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seleccionarDueñoResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.seleccionarDueñoResponseBody Body;
        
        public seleccionarDueñoResponse() {
        }
        
        public seleccionarDueñoResponse(consumirWebService.servicioAsmx.seleccionarDueñoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seleccionarDueñoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioAsmx.Dueños seleccionarDueñoResult;
        
        public seleccionarDueñoResponseBody() {
        }
        
        public seleccionarDueñoResponseBody(consumirWebService.servicioAsmx.Dueños seleccionarDueñoResult) {
            this.seleccionarDueñoResult = seleccionarDueñoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDueñoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDueño", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.insertarDueñoRequestBody Body;
        
        public insertarDueñoRequest() {
        }
        
        public insertarDueñoRequest(consumirWebService.servicioAsmx.insertarDueñoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDueñoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioAsmx.Dueños insDueño;
        
        public insertarDueñoRequestBody() {
        }
        
        public insertarDueñoRequestBody(consumirWebService.servicioAsmx.Dueños insDueño) {
            this.insDueño = insDueño;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDueñoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDueñoResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.insertarDueñoResponseBody Body;
        
        public insertarDueñoResponse() {
        }
        
        public insertarDueñoResponse(consumirWebService.servicioAsmx.insertarDueñoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarDueñoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarDueñoResult;
        
        public insertarDueñoResponseBody() {
        }
        
        public insertarDueñoResponseBody(bool insertarDueñoResult) {
            this.insertarDueñoResult = insertarDueñoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarDueñoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarDueño", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.ModificarDueñoRequestBody Body;
        
        public ModificarDueñoRequest() {
        }
        
        public ModificarDueñoRequest(consumirWebService.servicioAsmx.ModificarDueñoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarDueñoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public consumirWebService.servicioAsmx.Dueños modDueño;
        
        public ModificarDueñoRequestBody() {
        }
        
        public ModificarDueñoRequestBody(consumirWebService.servicioAsmx.Dueños modDueño) {
            this.modDueño = modDueño;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarDueñoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarDueñoResponse", Namespace="http://tempuri.org/", Order=0)]
        public consumirWebService.servicioAsmx.ModificarDueñoResponseBody Body;
        
        public ModificarDueñoResponse() {
        }
        
        public ModificarDueñoResponse(consumirWebService.servicioAsmx.ModificarDueñoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarDueñoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarDueñoResult;
        
        public ModificarDueñoResponseBody() {
        }
        
        public ModificarDueñoResponseBody(bool ModificarDueñoResult) {
            this.ModificarDueñoResult = ModificarDueñoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioAsmxDueñosSoapChannel : consumirWebService.servicioAsmx.servicioAsmxDueñosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioAsmxDueñosSoapClient : System.ServiceModel.ClientBase<consumirWebService.servicioAsmx.servicioAsmxDueñosSoap>, consumirWebService.servicioAsmx.servicioAsmxDueñosSoap {
        
        public servicioAsmxDueñosSoapClient() {
        }
        
        public servicioAsmxDueñosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioAsmxDueñosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioAsmxDueñosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioAsmxDueñosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioAsmx.registrosDueñosResponse consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.registrosDueños(consumirWebService.servicioAsmx.registrosDueñosRequest request) {
            return base.Channel.registrosDueños(request);
        }
        
        public consumirWebService.servicioAsmx.Dueños[] registrosDueños() {
            consumirWebService.servicioAsmx.registrosDueñosRequest inValue = new consumirWebService.servicioAsmx.registrosDueñosRequest();
            inValue.Body = new consumirWebService.servicioAsmx.registrosDueñosRequestBody();
            consumirWebService.servicioAsmx.registrosDueñosResponse retVal = ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).registrosDueños(inValue);
            return retVal.Body.registrosDueñosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.registrosDueñosResponse> consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.registrosDueñosAsync(consumirWebService.servicioAsmx.registrosDueñosRequest request) {
            return base.Channel.registrosDueñosAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioAsmx.registrosDueñosResponse> registrosDueñosAsync() {
            consumirWebService.servicioAsmx.registrosDueñosRequest inValue = new consumirWebService.servicioAsmx.registrosDueñosRequest();
            inValue.Body = new consumirWebService.servicioAsmx.registrosDueñosRequestBody();
            return ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).registrosDueñosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioAsmx.seleccionarDueñoResponse consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.seleccionarDueño(consumirWebService.servicioAsmx.seleccionarDueñoRequest request) {
            return base.Channel.seleccionarDueño(request);
        }
        
        public consumirWebService.servicioAsmx.Dueños seleccionarDueño(int id) {
            consumirWebService.servicioAsmx.seleccionarDueñoRequest inValue = new consumirWebService.servicioAsmx.seleccionarDueñoRequest();
            inValue.Body = new consumirWebService.servicioAsmx.seleccionarDueñoRequestBody();
            inValue.Body.id = id;
            consumirWebService.servicioAsmx.seleccionarDueñoResponse retVal = ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).seleccionarDueño(inValue);
            return retVal.Body.seleccionarDueñoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.seleccionarDueñoResponse> consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.seleccionarDueñoAsync(consumirWebService.servicioAsmx.seleccionarDueñoRequest request) {
            return base.Channel.seleccionarDueñoAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioAsmx.seleccionarDueñoResponse> seleccionarDueñoAsync(int id) {
            consumirWebService.servicioAsmx.seleccionarDueñoRequest inValue = new consumirWebService.servicioAsmx.seleccionarDueñoRequest();
            inValue.Body = new consumirWebService.servicioAsmx.seleccionarDueñoRequestBody();
            inValue.Body.id = id;
            return ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).seleccionarDueñoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioAsmx.insertarDueñoResponse consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.insertarDueño(consumirWebService.servicioAsmx.insertarDueñoRequest request) {
            return base.Channel.insertarDueño(request);
        }
        
        public bool insertarDueño(consumirWebService.servicioAsmx.Dueños insDueño) {
            consumirWebService.servicioAsmx.insertarDueñoRequest inValue = new consumirWebService.servicioAsmx.insertarDueñoRequest();
            inValue.Body = new consumirWebService.servicioAsmx.insertarDueñoRequestBody();
            inValue.Body.insDueño = insDueño;
            consumirWebService.servicioAsmx.insertarDueñoResponse retVal = ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).insertarDueño(inValue);
            return retVal.Body.insertarDueñoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.insertarDueñoResponse> consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.insertarDueñoAsync(consumirWebService.servicioAsmx.insertarDueñoRequest request) {
            return base.Channel.insertarDueñoAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioAsmx.insertarDueñoResponse> insertarDueñoAsync(consumirWebService.servicioAsmx.Dueños insDueño) {
            consumirWebService.servicioAsmx.insertarDueñoRequest inValue = new consumirWebService.servicioAsmx.insertarDueñoRequest();
            inValue.Body = new consumirWebService.servicioAsmx.insertarDueñoRequestBody();
            inValue.Body.insDueño = insDueño;
            return ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).insertarDueñoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consumirWebService.servicioAsmx.ModificarDueñoResponse consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.ModificarDueño(consumirWebService.servicioAsmx.ModificarDueñoRequest request) {
            return base.Channel.ModificarDueño(request);
        }
        
        public bool ModificarDueño(consumirWebService.servicioAsmx.Dueños modDueño) {
            consumirWebService.servicioAsmx.ModificarDueñoRequest inValue = new consumirWebService.servicioAsmx.ModificarDueñoRequest();
            inValue.Body = new consumirWebService.servicioAsmx.ModificarDueñoRequestBody();
            inValue.Body.modDueño = modDueño;
            consumirWebService.servicioAsmx.ModificarDueñoResponse retVal = ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).ModificarDueño(inValue);
            return retVal.Body.ModificarDueñoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<consumirWebService.servicioAsmx.ModificarDueñoResponse> consumirWebService.servicioAsmx.servicioAsmxDueñosSoap.ModificarDueñoAsync(consumirWebService.servicioAsmx.ModificarDueñoRequest request) {
            return base.Channel.ModificarDueñoAsync(request);
        }
        
        public System.Threading.Tasks.Task<consumirWebService.servicioAsmx.ModificarDueñoResponse> ModificarDueñoAsync(consumirWebService.servicioAsmx.Dueños modDueño) {
            consumirWebService.servicioAsmx.ModificarDueñoRequest inValue = new consumirWebService.servicioAsmx.ModificarDueñoRequest();
            inValue.Body = new consumirWebService.servicioAsmx.ModificarDueñoRequestBody();
            inValue.Body.modDueño = modDueño;
            return ((consumirWebService.servicioAsmx.servicioAsmxDueñosSoap)(this)).ModificarDueñoAsync(inValue);
        }
        
        public bool eliminarDueño(int eliDueño) {
            return base.Channel.eliminarDueño(eliDueño);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarDueñoAsync(int eliDueño) {
            return base.Channel.eliminarDueñoAsync(eliDueño);
        }
    }
}
